# region org.gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=false
# endregion
########################################################################################################################
# region mod
mod.group=io.github.leawind.perspectiveapicompat
mod.id=perspective_api_compat
mod.version=0.0-SNAPSHOT
mod.name=Perspective API Compat
mod.description=A client-side compatibility layer for Perspective API and other mods.
mod.author=Leawind
mod.license=MIT
mod.logo_file=logo.png
mod.home_url=https://github.com/Leawind/Perspective-API-Compat
mod.source_url=https://github.com/Leawind/Perspective-API-Compat
mod.issues_url=https://github.com/Leawind/Perspective-API-Compat/issues
mod.email=leawind@yeah.net
mod.perspective_api_version=1.5.0-beta
deps.fabricLoader=0.19.3
# endregion
